### ISSUE TITLE
Question- track mouth and change colors

### ISSUE THREAD

**Issue by doubletaketech** [eduardolundgren/tracking.js#107]
Your project is amazing!  I'm looking at it as a way to track a user's mouth (actually teeth) in the webcam and re-color their teeth.

Can I track just the mouth in the webcam or is that just for images?

Any suggestions on how to change the colors in real-time?  I know you can manipulate pixels in canvas.

Sorry this is not an "issue", but I don't see any discussion board for tracking.js .

Thanks,
Don

**Comment by eduardolundgren** [comment]
Closing this, feel free to reopen in case you need any more help.
