### ISSUE TITLE
Camera is not requested

### ISSUE THREAD

**Issue by conmarap** [eduardolundgren/tracking.js#111]
For the examples that require camera, tracking does not request the camera and the examples never start. Tried on Chrome, Firefox and IE.

**Comment by zenorocha** [comment]
Are you running the examples in `file:///`? You should start a local web server to run it.

**Comment by conmarap** [comment]
No, I have a webserver that runs the examples.

**Comment by zenorocha** [comment]
Is there any error in the console?

Everything works fine for us...

![screen shot 2015-01-16 at 3 16 07 pm](https://cloud.githubusercontent.com/assets/398893/5781574/a5e0acac-9d92-11e4-98e9-bf9094c92015.png)

**Comment by harksha** [comment]
I know this is closed, but maybe it will help someone in the future: camera will not be requested over http, only https!

**Comment by sorxrob** [comment]
@harksha then how can we develop then locally? LOL

**Comment by harksha** [comment]
@sorxrob you can use a tunnel like [ngrok](https://ngrok.com/) to do it
