### ISSUE TITLE
Question: Generate new Object Tracker

### ISSUE THREAD

**Issue by valepu** [eduardolundgren/tracking.js#112]
Hello,
I hope i'm not asking a dumb question, but i'd like to know how to generate training data in order to make a new tracker. 
I have no experience with computer vision but i have no fear to get my hands dirty, though it is not clear to me what i have to use to generate training data (if it's possible at the moment, that is). I have to do something similar to issue #109 my logos are monochromatic images on white paper (the concept is not that different than QR codes, just that they are made of one single color), from what i have understood i have to generate data for an implementation of the viola-jones algorithm (seems to be the right choice for my task, even though it's specialized in face detection) and then import it with the script contained in opencv_haarcascade_converter.html, is that right?

I can understand that it's not your responsability to provide a guide for that but, If possible, it would be nice to have a very brief guide or even just some suggestions on what software to use to do that would be apprecciated (i just need to be pointed in the right direction)

**Comment by valepu** [comment]
Maybe this will be of help if someone else wants to create new object trackers:
I have managed to generate a vector for tracking.js using gulp-convert-tjs.
1) Downloaded OpenCV and followed the instructions from this video: https://www.youtube.com/watch?v=WEzm7L5zoZE (used -featureType Haar instead of LBP to create a cascade.xml file). As i said in my first post, i have never used OpenCV so i didn't tweak any of the settings nor i used a good training sample, i was just trying to get to the end.
2) Installed gulp and gulp-convert-tjs through npm in a empty folder. 
This was very time and energy consuming and took me half a day, i had node and Visual Studio 2010 already but i had to install 
- python 2.7 (not sure if python 3 will do)
- Windows SDK for Windows 7 (if you get an error while installing it will probably be because you have already installed a version of Microsoft Visual C++ 2010 Redistributable, you have to uninstall it and installing Windows SDK will install it again...yes it won't just realize that you have it alredy installed and go on, it will actually fail the installation without a clear warning) 
- Visual Studio 2012 because it looks like node-expat won't compile with VS 2010. See https://github.com/node-xmpp/node-expat/issues/94 (there's no need to uninstall anything related to Visual Studio 2010, you just need to type "npm install gulp-convert-tjs --msvs_version=2012" to use Visual Studio 2012 to compile)
3) Followed the instructions from https://github.com/cirocosta/gulp-converter-tjs to create a gulp task

**Comment by eduardolundgren** [comment]
That sounds awesome @valepu.

Do you happen to have screenshots of `tracking.js` detecting your custom object? If so, post here please.

Would be good to do an automatic conversion task, e.g. having a folder inside `tracking.js` project that we drop HAAR XML files and the custom task based on `gulp-convert-tjs` to convert them automatically to the flattened array.

/cc @cirocosta

**Comment by valepu** [comment]
Sadly the training set was very bad and there were many false positives, now the project was put on hold because we don't have much time, but i'm looking forward into using your awesome library in another project sooner or later.

**Comment by cirocosta** [comment]
Thanks for all your effort @valepu ! I was thinking here, maybe it'd be of great benefit to test the produced training data against both tracking.js and pure opencv trackers persuing a great end for #98 . I do already have opencv setten up, having some time i could go for it. What do you think @eduardolundgren ? (Also, what about closing this issue and going back to #98 ?)

**Comment by eduardolundgren** [comment]
SGTM. Closing this one in favor of #98. Thank you.
