### ISSUE TITLE
Possible to track facial expression?

### ISSUE THREAD

**Issue by bildlich** [eduardolundgren/tracking.js#113]
Is it theoretically possible to use the tracking to ineptret a person's facial expression? E.g. determining how much a person is smiling by measuring the angle from the corner of one's mouth to the center?

**Comment by eduardolundgren** [comment]
For object detection we have the ViolaJones algorithm, which helps you find rectangles around the desired object. In order to detect facial expressions you need to extract relevant face key-points. There is a nice project that may interest you for that https://github.com/auduno/clmtrackr.
