### ISSUE TITLE
Detect Objects

### ISSUE THREAD

**Issue by jonathan0211** [eduardolundgren/tracking.js#116]
I started making a project that I will have to track objects. When the camera tracked the object it will have to get data from a data base and show to the user. In other words I need to use the tracker to find it's info in the data bases. Can I do with tracking.js? If the answer is yes, Can you help doing this?

**Comment by thiago-rocha** [comment]
Using tracking.js, do you wanna find a object in a video OR based on video content find something in your data bases?

**Comment by jonathan0211** [comment]
Something like this, I wanna do a markerless augmented reality system. So I would use tracking.js to identify the element and get the informations of this element in the data base and show to the user.

**Comment by thiago-rocha** [comment]
Ok, you first need training you data using OpenCV http://docs.opencv.org/doc/user_guide/ug_traincascade.html, after this you will need to convert the result to tacking.js format using the tracking.js Converter (https://github.com/eduardolundgren/tracking.js/pull/98), after this two steps will you be able to use tracking.js to find your objects just adding your training results (http://trackingjs.com/docs.html#trackers).

**Comment by jonathan0211** [comment]
Ok, I will take a look. If you have an exemple of something like this please give it to me.

**Comment by nfarve** [comment]
Is the full XML file data fed into the Converter?

**Comment by thiago-rocha** [comment]
@nfarve , please, create a new issue for your question.
