### ISSUE TITLE
From top to bottom

### ISSUE THREAD

**Issue by jhi0417** [eduardolundgren/tracking.js#117]
For http://trackingjs.com/examples/color_camera.html, I would like to implement the functionality that would recognize the color 'white' as a default and save the recognized color in a top-down fashion. If anyone could give an advice for this implementation, I would appreciate it! Thanks! 

p*s : for an example,
blue
red
blue
yellow
blue

**Comment by thiago-rocha** [comment]
Hey @jhi0417 , I'm trying understand what is your problem but i'm getting confused, could you please give me more details about what you want to do?

**Comment by jhi0417** [comment]
Hey @thiago-rocha thanks for taking a look at my post. I will try to explain better. First of all, when a camera recognizes the color on the screen, let's say I was wearing a blue hat, red shirt, and yellow pants, I would like to its information in an array [blue, red, yellow]. I hope I am explaining better :)

**Comment by thiago-rocha** [comment]
@jhi0417 , the color tracker needs know the color to be tracker before start, but you want, based on a object in camera's image, identify what is the object color. I'm right?

**Comment by jhi0417** [comment]
@thiago-rocha yes! exactly! thanks for pointing it out

**Comment by thiago-rocha** [comment]
This is a huge challenge to Computer Vision/Augmented Reality, cause you don't wanna find a specific color in a image, what you want is: based on image find a person, identify the clothes and get the colors. The better trackingjs tracker to help you is the Viola-Jones using the body training, but you will need process the result to identify the head/upper body/lower body and get the colors. Sorry, but is not that simple.

**Comment by jhi0417** [comment]
@thiago-rocha Hello! I think I overstated the problem. What I want is to find a specific color in an image. I attached images for the reference.
![52](https://cloud.githubusercontent.com/assets/6404020/7129650/3172913a-e231-11e4-8173-f16ca0eb9bf9.jpg) 
![screen shot 2015-03-13 at 4 34 01 pm](https://cloud.githubusercontent.com/assets/6404020/7129642/1f56e29e-e231-11e4-8931-6b6e0d3025db.png)

**Comment by thiago-rocha** [comment]
Do you want use trackingjs or OpenCV?

**Comment by jhi0417** [comment]
@thiago-rocha I want to use trackingjs :)

**Comment by thiago-rocha** [comment]
Ok, you can track this three different colors, and when you get a result from color tracker you will compare the X coordinate of this three color, something like this:
if (x-yellow > x-blue && x-blue > x-red) return true;

**Comment by jhi0417** [comment]
@thiago-rocha I see your idea, that is a good idea actually since I only need to recognize three colors and at most I will have six cases. thanks! by the way, I think I need to compare y coordinate of these colors; how am I going to access it?

**Comment by thiago-rocha** [comment]
Sorry, you right, this case needs use Y coordinate.

**Comment by jhi0417** [comment]
@thiago-rocha no problem! I also think I was careless when it comes to looking up the getting started tutorials! I am also taking a closer look at it, too! thanks for keeping the discussion going! I really appreciate it! http://trackingjs.com/docs.html

**Comment by jhi0417** [comment]
@thiago-rocha I also think it is just fine to take a picture then process the still image with tracking.js :+1:

**Comment by jhi0417** [comment]
Well, I think I am moving onto another implementation. I just would like to take a snapshot likehttp://davidwalsh.name/demo/camera.php and process that image using tracking.js (color) like http://trackingjs.com/examples/color_hello_world.html. If anyone could suggest me an idea how I can approach this between two processes, I would appreciate it!

**Comment by jhi0417** [comment]
@thiago-rocha I think I will try to use this js library http://pixlcore.com/demos/webcamjs/demos/basic.html and hope to process the image and returns the results in an array; would you have any idea how to access the image data using tracking.js?

**Comment by jhi0417** [comment]
Okay, I have implemented the basic html and js codes that take the picture and save as <img id ="img" ... > however, when I click the button to analyze the image, it says undefined is not a function.. anyone has an idea? http://jangheei.com/april15/v1/test1.html
