### ISSUE TITLE
dat-gui is missing

### ISSUE THREAD

**Issue by berak** [eduardolundgren/tracking.js#135]
referenced from several files, but does not exist in zip or in repo here

https://github.com/eduardolundgren/tracking.js/search?utf8=%E2%9C%93&q=dat-gui

**Comment by eduardolundgren** [comment]
This is used for the examples only.

**Comment by berak** [comment]
yes, that's true. (nice library, btw, keep on rocking !!)

still, if you have it somewhere, a link would be highly appreciated.

**Comment by eduardolundgren** [comment]
Sure. C

**Comment by carloshpds** [comment]
:+1:

**Comment by eduardolundgren** [comment]
Fixed on https://github.com/eduardolundgren/tracking.js/issues/135

**Comment by eduardolundgren** [comment]
Fixed on https://github.com/eduardolundgren/tracking.js/pull/184.
