### ISSUE TITLE
How to create or add new training files like eye.js,face.js and mouth.js ?

### ISSUE THREAD

**Issue by ripper2hl** [eduardolundgren/tracking.js#136]
For example i have one image from radiography and i want detect the tumor in this image, its possible with tracking.js ?,(its my homework ) , i like this project and the tumor detection its a great example for add
![imagen](https://cloud.githubusercontent.com/assets/2611201/10109381/2a45fdfc-638c-11e5-9f11-8c42063a16ff.png)

**Comment by thiago-rocha** [comment]
@ripper2hl , use trackingjs isn't a good approach for this type of problem, what's the most common approach it is Image-Processing Techniques like filter, image segmentation, image classification...

**Comment by ripper2hl** [comment]
@thiago-rocha thanks for the info, i close this issue
