### ISSUE TITLE
Camera example on tracking.js no longer works in Chrome

### ISSUE THREAD

**Issue by xdumaine** [eduardolundgren/tracking.js#143]
Chrome 47 requires pages using `getUserMedia` to be served over HTTPS, so none of the Camera examples work now. I'd suggest using CloudFlare for DNS for free SSL.

See console warning on [this page](http://trackingjs.com/examples/face_camera.html):

> `getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.`

**Comment by eduardolundgren** [comment]
We definitely need to move over HTTPS then. Thank you for reporting.

**Comment by joshuazong** [comment]
Hello,

This also appears to be an issue for IE as well.

**Comment by xdumaine** [comment]
IE doesn't support getUserMedia at all.

**Comment by zenorocha** [comment]
trackingjs.com now runs on HTTPS and a bug related to `getUserMedia` has been fixed on [1.1.2](https://github.com/eduardolundgren/tracking.js/releases/tag/v1.1.2). Thanks @xdumaine!

**Comment by sykov** [comment]
Hey, 

I'm using tracking.js version 1.1.2, but i doesn't work on IE, and works perfectly in Chrome. any suggestions?

**Comment by sorxrob** [comment]
@zenorocha  what about developing locally? Are we able to use it?

**Comment by murat-aka** [comment]
#269

**Comment by tj-creative** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
