### ISSUE TITLE
Bring the accuracy to the camera for cheap

### ISSUE THREAD

**Issue by youngho1** [eduardolundgren/tracking.js#147]
Use LED Gloves with High White Sensitivity

http://www.bestbuy.com/site/insignia-led-gloves-with-blue-led-lights-white/4336600.p?id=1219736715294&skuId=4336600

**Comment by thiago-rocha** [comment]
Indeed use this gloves could bring more accuracy for a application using the Color tracking, but you can't have a background in a different color.
Let us know if you have any problem with trackingjs on your "White Gloves Tracker".
