### ISSUE TITLE
Is anyone maintaining this anymore?

### ISSUE THREAD

**Issue by abagshaw** [eduardolundgren/tracking.js#172]
Just wondering - seems like there are a lot of really helpful pull requests just sitting there that aren't being merged...

**Comment by eduardolundgren** [comment]
@abagshaw First of all thanks for asking, this will help me clarify with the rest of the community. 

As many other open-source projects maintained by a couple of persons we are struggling at the well known open-source vs. work-life balance. The project is in **maintenance mode** right now, urgent bug-fixes are merged, new features and enhancements are put on hold to avoid breaking existing codebase.

It's been a while I am looking for contributors that can help maintaining the library. I have some guesses why it's not easy to find contributors for libraries like tracking.js, it involves very specific knowledge about a subject and most of the people willing to learn computer vision are in the academic world. On the other hand, lots of things can be contributed without being a expert in the matter, like general bugs, build system issues etc.

Worse case scenario, by early next year we will release a new version with all (or most of) those open issues merged or resolved, in addition we want to add new features to improve augmented reality usage. Inspired by new technologies like Snapchat filters and Pokémon Go, in the next couple of years computer vision and augmented reality on the web will grow exponentially. We need to be prepared for that. If you think you can help somehow feel free to contribute, that's a good moment to join.

I hope that clarified your question, and thanks again for bringing that up.

**Comment by Master244** [comment]
I would really like to contribute to this project :)
