### ISSUE TITLE
Change color of Draw Something line.

### ISSUE THREAD

**Issue by blepage** [eduardolundgren/tracking.js#186]
Hello how can you change the color of the line produced by the color tracker within Draw Something example. Help would be much appreciated. Code is standard to initial build.

**Comment by eduardolundgren** [comment]
Yes you can register a new color rule or using the existing ones. To register a new color you can do:

```js
tracking.ColorTracker.registerColor('myColor', function(r, g, b) {
  if (r < 50 && g > 200 && b < 50) {
    return true;
  }
  return false;
});
```

On the example you can just change it here to the new color name, https://github.com/eduardolundgren/tracking.js/blob/master/examples/color_draw_something.html#L64.
