### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by datwheat** [eduardolundgren/tracking.js#188]
Would this library be possible to use with React Native?

**Comment by eduardolundgren** [comment]
I guess so, I have never tried. Did you try running it in React Native?

**Comment by hugohow** [comment]
Did someone try ?

**Comment by cyrusbehr** [comment]
So whats the verdict!

**Comment by donfour** [comment]
???plz

**Comment by sibelius** [comment]
related to https://github.com/eduardolundgren/tracking.js/issues/234

**Comment by augustolazaro** [comment]
It not works well with React Native. I've tried an implementation here:
![screenshot_1508776853](https://user-images.githubusercontent.com/7659279/31901503-5d188fea-b800-11e7-9e54-cb5b687da37f.png)

**Comment by egunsoma** [comment]
Has anyone tried it with WebView?

**Comment by moddatherrashed** [comment]
@augustolazaro of course it won't work when you are using document in react native, the question was if you could track any image !
