### ISSUE TITLE
Insecure resource sharing on Racing Car example

### ISSUE THREAD

**Issue by jvke** [eduardolundgren/tracking.js#201]
`Mixed Content: The page at 'https://trackingjs.com/examples/color_hexgl.html' was loaded over HTTPS, but requested an insecure resource 'http://pablocp.github.io/HexGL/'. This request has been blocked; the content must be served over HTTPS.`

**Comment by jvjvjv** [comment]
Visit the source code for that example at https://github.com/pablocp/HexGL/ -- it will tell you how to run the project locally.

The issue you describe is not a fault of tracking.js libraries, but of the site's attempts to mix secure and insecure content.
