### ISSUE TITLE
[Question] Why it needs a web server?

### ISSUE THREAD

**Issue by AdRiAnIlloO** [eduardolundgren/tracking.js#211]
So far I didn't find any kind of documentation on the official web nor on Google searches on why tracking.js needs a web server (and why, with less intrigue, requires it to be accessed through HTTPS) in order to work. I could only assume it does threaded/parallel work on the server and sends real time results to the client DOM...

I am looking for a simple and concrete enough answer on the form that it shows the dependencies this library relies on, in order to justify this web server requirement fact. Otherwise, if it's all about browser incapabilities or default disabled flags when executing tracking.js locally without web server (which is the typical issue in some contexts), please mention them aswell.

Thanks!

**Comment by AnthyG** [comment]
As far as I am aware of, at least chrome actually requires https for websites that access devices like the camera or microphone.

As tracking.js normally requires a camera to work, you need a webserver to access it via https.

`localhost` is actually a https-like domain too I think, so you could just access the webserver without any certificate..

Just FYI, I don't consider myself as an expert. :)

**Comment by AdRiAnIlloO** [comment]
Seems logical. Thanks

**Comment by murat-aka** [comment]
#269
