### ISSUE TITLE
Custom object tracker issue

### ISSUE THREAD

**Issue by thestrayed** [eduardolundgren/tracking.js#225]
I try to create custom tracker using my trained xml from opencv. I'm following the link in `/assets/*.js` in those js file on the 1st line. it's said converted by using [XML to JSON](http://www.freeformatter.com/xml-to-json-converter.html)
Then I use `opencv_haarcascade_converter.html` to convert that JSON file to JS. and I replaced all the extra tab 
e.g. `[[-1,-1.3526400327682495,8],[0,11,8,-1,6,2,11,4,2,-0.0461773201823235]]` to `[-1,-1.3526400327682495,8,0,11,8,-1,6,2,11,4,2,-0.0461773201823235]` 
I saved that as smile.js so and tried it on browser. Camera is launched but video didn't show up at all and I tried inspect it in console but nothing shown up. 
Anyone has an idea why?

**Comment by revolunet** [comment]
do you have testable or reproductible code ?
