### ISSUE TITLE
Add support for Safari 11/remove deprecated getUserMedia API

### ISSUE THREAD

**Issue by ted-piotrowski** [eduardolundgren/tracking.js#228]
First off, thank you for a great library. I managed to implement my pet project [Slouch cam](https://slouchcam.com) with minimal effort. Thank you! (I did offload the ViolaJones computations onto a worker thread to improve responsiveness. Happy to share this work if interested.)

My issue is more pragmatic. Safari 11.0 will be implementing User Media functionality, however, they will be using the newer `navigator.mediaDevices.getUserMedia` api, instead of the deprecated `navigator.getUserMedia`. Support for this newer version of `getUserMedia` does not exist in tracking.js.

PR: https://github.com/eduardolundgren/tracking.js/pull/229

**Comment by jeromeetienne** [comment]
It has been merged. thanks for the contribution :)

**Comment by tschiemer** [comment]
heja! Thanks for the library!

Just a sidenote, it would seem that on the official website you still are using version 1.1.2 wherein this fix (as of 1.1.3) is not yet included.

https://trackingjs.com/bower/tracking.js/build/tracking-min.js
