### ISSUE TITLE
Count number of faces

### ISSUE THREAD

**Issue by sunnykeerthi** [eduardolundgren/tracking.js#230]
Hi,

 This is essentially not a bug just looking for a feature. Is there a way that I can count the number of faces in a given Image.

 For example I've three persons in front of a webcam and I'm having 2 pages say, **Success.html** and **error .html** and as part of the underlying way to judge the redirection to _Success_ or _error_ pages the condition would be, if only one face is detected, it should be sent to _success_, else, it should be sent to _error_ . 

Please let me know if I have a feature available here already to perform this task and how can I do this.

If not, where can I get such similar reference.

Thanks,
Rakesh

**Comment by revolunet** [comment]
The [first example in the documentation](https://trackingjs.com/docs.html) show that `event.data.length` should give you the number of detected objects.


<img width="645" alt="capture d ecran 2017-07-01 a 23 53 31" src="https://user-images.githubusercontent.com/124937/27765679-90f6be00-5eb8-11e7-8b84-5c5f2ab2c7cf.png">

About the redirection logic, this is not tracking.js related, just change `document.location` to redirect.

**Comment by jeromeetienne** [comment]
closing, dont hesitate to reopen if needed

ps: @revolunet good to see you here :)
