### ISSUE TITLE
use es6/7 babel

### ISSUE THREAD

**Issue by sibelius** [eduardolundgren/tracking.js#234]

**Comment by jeromeetienne** [comment]
it wont provide any feature advantage and require a whole rewrite. Lets focus on pragmatic advances which add more to the user.

there is way enougth to do already :)

**Comment by sibelius** [comment]
I think using es6/7 with babel would bring more contributors for this package

it is not working with react native for now (https://github.com/eduardolundgren/tracking.js/issues/188)
because depends on web stuff, like `document`

**Comment by jgcmarins** [comment]
@jeromeetienne any chances to reopen this one?

**Comment by sibelius** [comment]
would u accept a PR to gradually move this to es6 and babel?
