### ISSUE TITLE
React example

### ISSUE THREAD

**Issue by howardkitto** [eduardolundgren/tracking.js#242]
Hi

Do you have any examples of the best practice for using tracking.js in a React project? (Ideally using create-react-app)

Huge thanks

**Comment by howardkitto** [comment]
Here is the issue that I'm having using tracking.js with React
[https://stackoverflow.com/questions/45676768/computer-vision-with-react](url)

**Comment by howardkitto** [comment]
For anyone who is interested, this is how you can get tracking.js working with React
https://github.com/howardkitto/react-tracking

**Comment by ggsjyoon** [comment]
Hi. @howardkitto. I tried your example but it seems that your example is not using `tracking.js`.

This line is commented out `// import trackVideo from './computerVision/trackVideo'` in `App.js` and I tried your code after `yarn remove tracking` and it still worked. Do you have other working example for `create-react-app` and `tracking.js`?

Please correct me if I got something wrong. Thanks.
