### ISSUE TITLE
Is possible recognition gender?

### ISSUE THREAD

**Issue by renanbastos93** [eduardolundgren/tracking.js#244]
Someone can me speak if is possible identification gender of the people if it's male or female?

**Comment by renanbastos93** [comment]
@zenorocha Hey man, you can I help-me?

**Comment by thiago-rocha** [comment]
The trackingjs algorithms can't identify the gender for now.

**Comment by renanbastos93** [comment]
@thiago-rocha Thanks, I will to study this algorithm for I try implement in this lib.
