### ISSUE TITLE
Demo not working. Error: Cannot capture user camera.

### ISSUE THREAD

**Issue by mankamhung1** [eduardolundgren/tracking.js#255]
It was working yesterday with colour detection on camera.

But when I open my web with the implementation, there's the error on console and camera failed to be turned on.
* Even the examples in "https://trackingjs.com" are not working, the same error appears in the console.

Details are as below (* the words "anonymous" after the second "at" with angle brackets cannot be shown):

Uncaught (in promise) Error: Cannot capture user camera.
    at tracking-min.js:8
    at <anonymous>

**Comment by mankamhung1** [comment]
It's working again now. Maybe someone has fixed it.

**Comment by murat-aka** [comment]
#263

**Comment by murat-aka** [comment]
#269
