### ISSUE TITLE
tracker.stop() not stopping .on('track') from emitting

### ISSUE THREAD

**Issue by Hoopstr42** [eduardolundgren/tracking.js#258]
When stop() is called the tracker is not stopping.  Here is a simplified version of my code. 

<video id="video" autoplay muted playsinline></video>

this.tracker = new tracking.ObjectTracker('face');
this.tracker.on('track', this._tracking.bind(this));

this.constraints = {
          audio: false,
          video: {
            width: {min: 640, ideal: 1280, max: 1280},
            height: {min: 360, ideal: 720, max: 720},
            facingMode: 'environment'
          },
          camera: true
};

this.myTracking = tracking.track(this.$.video, this.tracker, this.constraints);

_tracking: function(event) {
        console.log('tracking');
        event.data.forEach(function(rect) {
          console.log('rect',rect);
          if(rect){
            this.myTracking.stop();
        }
}.bind(this);

After stop is called the 'tracking' log entry continues to run.
The only way I can get it to stop is to do this.$.video.src = ' ';
Which crashes the tracking loop.

**Comment by Hoopstr42** [comment]
![tracking error](https://user-images.githubusercontent.com/2999469/32567287-d10addce-c488-11e7-8aae-e42c86c02642.png)

**Comment by Hoopstr42** [comment]
![tracking error](https://user-images.githubusercontent.com/2999469/32567287-d10addce-c488-11e7-8aae-e42c86c02642.png)

**Comment by Hoopstr42** [comment]
This is a screen shot of the console log

![tracking error](https://user-images.githubusercontent.com/2999469/32567287-d10addce-c488-11e7-8aae-e42c86c02642.png)

**Comment by Hoopstr42** [comment]
This is a screen shot of the console log

![tracking error](https://user-images.githubusercontent.com/2999469/32567287-d10addce-c488-11e7-8aae-e42c86c02642.png)

**Comment by Hoopstr42** [comment]
This is a screen shot of the console log

![tracking error](https://user-images.githubusercontent.com/2999469/32567287-d10addce-c488-11e7-8aae-e42c86c02642.png)

**Comment by markos92i** [comment]
This is happening to me too, and is annoying

**Comment by murat-aka** [comment]
#102

**Comment by amilyhao** [comment]
I still have this problem, tracker.stop() not stopping .on('track') from emitting

**Comment by amilyhao** [comment]
> This is happening to me too, and is annoying

Excuse me，have this problem resolved.

**Comment by amilyhao** [comment]
> When stop() is called the tracker is not stopping. Here is a simplified version of my code.
> 
> this.tracker = new tracking.ObjectTracker('face');
> this.tracker.on('track', this._tracking.bind(this));
> 
> this.constraints = {
> audio: false,
> video: {
> width: {min: 640, ideal: 1280, max: 1280},
> height: {min: 360, ideal: 720, max: 720},
> facingMode: 'environment'
> },
> camera: true
> };
> 
> this.myTracking = tracking.track(this.$.video, this.tracker, this.constraints);
> 
> _tracking: function(event) {
> console.log('tracking');
> event.data.forEach(function(rect) {
> console.log('rect',rect);
> if(rect){
> this.myTracking.stop();
> }
> }.bind(this);
> 
> After stop is called the 'tracking' log entry continues to run.
> The only way I can get it to stop is to do this.$.video.src = ' ';
> Which crashes the tracking loop.

Excuse me，have this problem resolved.
