### ISSUE TITLE
Landmark Indices

### ISSUE THREAD

**Issue by msj121** [eduardolundgren/tracking.js#261]
Does someone already have a point to index list for the Landmark Tracker?
Like Left Jaw is index 0 for example
https://github.com/eduardolundgren/tracking.js/blob/master/src/trackers/LandmarksTracker.js

**Comment by msj121** [comment]
For anyone interested, 0 is left side of face down to chin at 4, then to right side up to 8.
Eyebrows are from 9 to 14
Nose 15 to 18
Mouth 27 to 30

**Comment by murat-aka** [comment]
#279
