### ISSUE TITLE
Racing Car Example doesn't work 

### ISSUE THREAD

**Issue by prashant-andani** [eduardolundgren/tracking.js#277]
Racing Car Example doesn't work 
**Where**: https://trackingjs.com/examples/color_hexgl.html
**Cause**: color_hexgl.html:72 Mixed Content: The page at 'https://trackingjs.com/examples/color_hexgl.html' was loaded over HTTPS, but requested an insecure resource 'http://pablocp.github.io/HexGL/'. This request has been blocked; the content must be served over HTTPS

Cause is clear that we are trying to load "http" Url over "https"

**Comment by murat-aka** [comment]
#201
