### ISSUE TITLE
How to track a basic shape? (Not an issue)

### ISSUE THREAD

**Issue by palafoxernesto** [eduardolundgren/tracking.js#290]
Hi i am new to tracking.js and CV as well.

I want to be able to track basic shapes like rectangle, square or circles with the camera. 

I understand that i can use a trained model created in opencv converted to json.

Is this the right way to go for basic shape detection?

Can anyone point me in the right direction?

Any help will be appreciated.

**Comment by murat-aka** [comment]
use color tracking for start.

https://trackingjs.com/examples/color_hello_world.html

**Comment by darshan78261992** [comment]
> Hi i am new to tracking.js and CV as well.
> 
> I want to be able to track basic shapes like rectangle, square or circles with the camera.
> 
> I understand that i can use a trained model created in opencv converted to json.
> 
> Is this the right way to go for basic shape detection?
> 
> Can anyone point me in the right direction?
> 
> Any help will be appreciated.

Even I am searching like this
