### ISSUE TITLE
How can I rotate 90deg web camera to detect faces?

### ISSUE THREAD

**Issue by david43** [eduardolundgren/tracking.js#373]
Hi,
How can I rotate 90deg web camera to detect faces?

**Comment by murat-aka** [comment]
https://www.w3schools.com/tags/canvas_rotate.asp

**Comment by david43** [comment]
> https://www.w3schools.com/tags/canvas_rotate.asp

It just rotate the canvas,but did not rotate the video source

**Comment by david43** [comment]
I try to use canvas to track,
but I got some error.
`			tracking.track('#canvas_d', vm.tracker);
`

`TypeError: Cannot read property 'getImageData' of null
`

**Comment by murat-aka** [comment]
https://github.com/eduardolundgren/tracking.js/blob/master/examples/face_camera.html

**Comment by david43** [comment]
found the problem.
It did not support pixi.webgl
