### ISSUE TITLE
Add "Maintainers wanted!" and funding banner 

### ISSUE THREAD

**Issue by fatso83** [eduardolundgren/tracking.js#385]
This project seems great, but it seems PRs have not been merged since 2018, indicating too much stress landing on the initial contributors. Maybe you should actively seek some help from people with more time to spend?

Feel free to [take some inspiration from us at Sinon](https://github.com/sinonjs/sinon/) as we have felt the pain of too many issues landing on our doorstep. We have entries for how to fund us using Open Collective, how to get started contributing and calls for additonal maintainers.

**Comment by fatso83** [comment]
Tips
https://www.firsttimersonly.com/
https://up-for-grabs.net/#/

**Comment by sushant12** [comment]
this seriously needs to be taken into consideration

**Comment by eduardolundgren** [comment]
Thank you for the suggestion. Added a "Maintainers Wanted" banner in this commit https://github.com/eduardolundgren/tracking.js/commit/0edde5fc2bc21aa92f4339459f50234fafbbb2ab
