### ISSUE TITLE
Decouple from DOM/make it node-compatible

### ISSUE THREAD

**Issue by rexxars** [eduardolundgren/tracking.js#47]
Hi,

I'd love to try and use tracking.js on the server-side with node.js. LearnBoost has an awesome module called node-canvas (https://github.com/learnboost/node-canvas) which implements the canvas API using a Cairo backend.

I don't think it would be too hard to decouple tracking.js from the DOM. A couple of points that are needed or would make this easier to achieve:
- Being able to pass a canvas instance instead of creating one in the library - this would also probably make it clear how to use it for a standalone canvas, such as drawing a static PNG to a canvas and running the recognition on it
- Concider separating some of the logic into different modules/files so that the webcam/getUserMedia-related parts doesn't have to be included in node.js
- Register tracking.js as an UMD-module (https://github.com/umdjs/umd) instead of setting it on window
- Perhaps implement the matchers as UMD-modules as well, so they are easy to use in node.js, the browser and using AMD-loaders such as RequireJS

I'd be happy to take a look and try to implement some of this stuff, but I want to know if you agree with the suggestions first, and if you have any plans to do this yourselves.

**Comment by IonicaBizau** [comment]
I've successfully used tracking.js on the server and build a module to detect faces. For those who want to do something similar, here is the source code: https://github.com/IonicaBizau/face-detectify

**Comment by m1lk1way** [comment]
@IonicaBizau can it be used to detect something from video stream?

**Comment by IonicaBizau** [comment]
Currently no, but maybe we can do it.
